--180) USE CASES : OPTIMIZE PERFORMANCE
USE SalesDB

SELECT * FROM INFORMATION_SCHEMA.TABLES

--CTAS(CREATE TABLE AS SELECT)
SELECT
	DATENAME(MONTH, OrderDate) OrderMonth,
	COUNT(OrderID) TotalOrders
INTO Sales.MonthlyOrders
FROM Sales.Orders
GROUP BY DATENAME(MONTH, OrderDate)

--AFTER CREATING CTAS TABLEN WE CAN SELECT QUERY
SELECT * FROM Sales.MonthlyOrders

--IF WANT REMOVE THE TABLE
DROP TABLE Sales.MonthlyOrders


--T-SQL(Transact-SQL)
IF OBJECT_ID('Sales.MonthlyOrders','U') IS NOT NULL
	DROP TABLE Sales.MonthlyOrders
GO
SELECT
	DATENAME(MONTH, OrderDate) OrderMonth,
	COUNT(OrderID) TotalOrders
INTO Sales.MonthlyOrders
FROM Sales.Orders
GROUP BY DATENAME(MONTH, OrderDate)


--AFTER CREATING CTAS TABLEN WE CAN SELECT QUERY
SELECT * FROM Sales.MonthlyOrders



--185) TEMP Syntax & Example (AFTER SESSION OR CLOSE THE SQL SERVER APPLICATON END THE TEMP TABLE CLEAR)
SELECT
*
INTO #Orders
FROM Sales.Orders

--AFTER CREATING TEMP TABLE WE CAN SELECT QUERY
SELECT * FROM dbo.#Orders

DELETE FROM dbo.#Orders WHERE OrderStatus='Delivered'


--AFTER DELETE THE DELIVERED ROWS FROM TEMP TABLE WE CAN SELECT QUERY
SELECT * FROM dbo.#Orders